### ISSUE TITLE
Impact 4.7 for MultiMC

### ISSUE THREAD

**Issue by KGriss** [ImpactDevelopment/ImpactIssues#1450]
Can you update the MultiMC version to Impact 4.7 ?
[https://github.com/ImpactDevelopment/ImpactClient/wiki/Installing-with-MultiMC](url)

**Comment by lmore377** [comment]
Try this json file. I haven't tested discord rpc but the game launches and I can join servers and everything
[me.zero.clarinet.Impact.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3433711/me.zero.clarinet.Impact.txt)

**Comment by GitHub0202** [comment]
^^ This is for 1.12.2 not 1.13.2 :(
and its not in the same format, so I had to merge this into the older Version it doesnt work with 1.13.2

**Comment by TheCompieter** [comment]
not working 


Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Impact 4.6 1.12.2' failed to process:
https://impactdevelopment.github.io/maven/cabaletta/baritone-api/1.2.8/baritone-api-1.2.8.jar
https://impactdevelopment.github.io/maven/com/github/ImpactDevelopment/Impact/4.7.2-1.12.2/Impact-4.7.2-1.12.2.jar

**Comment by TheCompieter** [comment]
it seems those file don't exist anymore on the server

**Comment by TheCompieter** [comment]
i tried to update it myzelf but failed here is the file and the error

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Impact 4.6 1.12.2' failed to process:
https://github.com/ImpactDevelopment/ImpactReleases/releases/download/4.7.2-1.12.2/Impact-4.7.2-1.12.2.jar/com/github/ImpactDevelopment/Impact/4.7.2-1.12.2/Impact-4.7.2-1.12.2.jar
https://github.com/cabaletta/baritone/releases/download/v1.2.8/baritone-api-1.2.8.jar/cabaletta/baritone-api/1.2.8/baritone-api-1.2.8.jar

[me.zero.clarinet.Impact.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3438262/me.zero.clarinet.Impact.txt)

**Comment by TheCompieter** [comment]
nvm i fixed it
[me.zero.clarinet.Impact.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3438278/me.zero.clarinet.Impact.txt)

**Comment by TheCompieter** [comment]
we only need the 1.13.2 version i will try too get that too work but i can't promis it.

**Comment by leijurv** [comment]
Can someone confirm that txt works, and provide one for 1.14.3 4.7.2? I'll update the wiki page I guess

**Comment by LeafHacker** [comment]
Iirc it should just be a case of copying the new libs object into the multimc JSON and maybe adding the multimc properties to each lib

**Comment by TheCompieter** [comment]
fixed impact 4.7 1.13.2 it work and i already put it on the wiki i only have too improve the 1.12.2 one a bit

**Comment by YurtCurcle** [comment]
Is there a fix available for 1.14.4?

**Comment by TheCompieter** [comment]
@YurtCurcle i will when i have time update it too 1.14.4

**Comment by LeafHacker** [comment]
This isn't really an issue in impact, so closing. See ImpactDevelopment/Installer#49 for progress on the installer supporting multimc. See [the wiki](https://github.com/ImpactDevelopment/ImpactIssues/wiki/Installing-with-MultiMC) for community maintained instructions on how to use impact with multimc right now

**Comment by TheCompieter** [comment]
it's already updated thanks for updating it.
