### ISSUE TITLE
Properly follow HTTP redirects

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactIssues#1660]
Receiving a HTTP redirect response currently leads to undefined behaviour (usually crashing) because we treat it as a good response rather than checking the response code and handling things from there.

This means we can't make use of HTTP redirects from `impactdevelopment.github.io` to `impactclient.net` 😭 

We should consider back-porting a fix to previous Impact releases...

**Comment by leijurv** [comment]
we do not backport

if people were willing to update to backported patches they'd be willing to update the whole client, no?

**Comment by LeafHacker** [comment]
Not in scenarios where impact stopped supporting a specific mc version or where they wish to stick with a specific major version due to changes they don't like in newer versions.

Sure, if they are only using the old version because they don't know to/how to update then they won't, but if we ever made use of this fix, it'd break anything that doesn't have the fix.

**Comment by leijurv** [comment]
Given that this https://github.com/ImpactDevelopment/Resources/blob/master/data/references.json can be pointed at new URLs I don't think it should be that much of an issue, this file just needs to stay at its current URL

**Comment by leijurv** [comment]
But it looks like references doesn't apply to every json: specifically, `assets.json` isn't covered. Also `maven.refmap.json` but that's a different situation.

**Comment by LeafHacker** [comment]
> Also `maven.refmap.json` but that's a different situation.

Less worried about the installer since we specifically haven't done a 1.0 so that we can break stuff while we figure things out.




> this file just needs to stay at its current URL


> But it looks like references doesn't apply to every json: specifically, `assets.json` isn't covered.

Which means we have to keep (at least legacy) files at those locations. If we ever move to a new system in the future they will just end up being deprecated and left unmodified.

I guess that is better than backporting redirects

**Comment by leijurv** [comment]
`we specifically haven't done a 1.0 so that we can break stuff while we figure things out.` no one depends on the installer but us...  i don't attach any weight to the fact that the version number may begin with a 0 or a 1 lol

assets.json and references.json is all that needs to stay for old (pre 4.7.X) clients. maven.refmap.json isn't that big of a deal, it can stay for 4.7.X to update. Since 4.7.X has the in client updater it shouldn't be that big of an issue I don't think.

There is also backgrounds.json and all the images for the main menu, but I think we agreed (please correct me if I'm wrong though) that that should stay simply for the insane bandwidth of >100mb of images per install (would blow through heroku bandwidth caps, >$500/mo on aws, etc).
I wonder if maybe we should just move backgrounds.json (i.e. leave the current one in place,  make a new one on impactclient.net/backgrounds.json or whatever, but instead of just filenames, it should be a list of full image URLs, even if the URLs still point back to impactdevelopment.github.io/Resources/textures/XXXXX)

**Comment by LeafHacker** [comment]
for image hosting I'm happy using something like imgur (we've done this in the past for cape textures and stuff, not sure if there's any advantage to specific image hosts), but for things like jsons i'd like it to be defined by refs.json and ideally on the impactclient domain

> i don't attach any weight to the fact that the version number may begin with a 0 or a 1 lol

Was just pointing out that the installer and it's infrastructure is still in development rather than being stable/finished

**Comment by leijurv** [comment]
ok but i autated over getting the exact highest resolution and i don't want imgur to compress it xD

**Comment by leijurv** [comment]
Tentatively, I think we only need to follow redirects for the references.json, since as of now that is the only resource that we get by a hardcoded URL. We then look into the contents of references.json for the URLs of every other resource (i.e. if we want to move one of those we can just change the URL references.json points to instead of redirecting). So only one place needs to be hardened against redirects I think.
