### ISSUE TITLE
Seed Bruteforcing

### ISSUE THREAD

**Issue by j13li78** [ImpactDevelopment/ImpactIssues#1776]
**Describe the solution you'd like**
The Module should be able to retrieve the seed from bruteforcing it with the generated chunks.

**Describe alternatives you've considered**
Using generated structures might also work suchs as strongholds villages.

**Additional context**

**Comment by devatator** [comment]
actually i read this from this page :https://gaming.stackexchange.com/questions/95387/find-a-minecraft-smp-server-seed-based-on-known-locations 
it says :"As a programming task, it's identical to the least efficient method of password cracking. We can't reverse-calculate the seed no matter how many landmark coordinates we have, because the type of calculation Minecraft uses for seed generation is one-way. Thus, what such a program would have to do is try every seed until it finds one that matches the landmarks.

In computer security terms this is called a brute-force attack, and it can take a very long time:

Minecraft's seeds have 18 quintillion possible values.
A GPU-based password cracker on consumer-grade hardware today, very loosely, can try about a billion numbers a second, given a target result (such as our landmarks).
1 quintillion is a billion billion.
That gives us about 18 billion seconds needed to try every possible seed.
On average we will have to only try half the seeds, so that brings us down to an average of 9 billion seconds to find a match.
9 billion seconds is over 285 years.
In reality the program would have to run world-generation (or some kind of faked world generation) on every seed in order to find out if it matches our landmarks, so multiply 285 years by how long it takes Minecraft to start a new world. If we're generous and say a fake-generation takes only 3 seconds, that gives us 856 years to find a match, on average.
And all that is ignoring the question of how the program would handle the fact that our coordinates of landmarks are going to be guesses (which block in a village is the coordinate the world generator got from the seed?) and not exact matches for what the seed actually produced. That adds at least a few processor cycles to every time the program needs to check a particular seed for matches.

So as you can see, the idea is lovely, but in practice finding a seed from landmark coordinates is impractical enough that no-one is going to write such a program – by the time it finishes running, we'd all be dead (and Minecraft will likely have changed its world-generation again…). At least, not practical until we have quantum computers." so this wont happen anytime soon

**Comment by VirxEC** [comment]
damn, schooled

**Comment by ZeroMemes** [comment]
The only way you can reasonably find world seeds is from bedrock formations and slime chunk locations. Programs already exist to do that.

**Comment by devatator** [comment]
Actually the bedrock pattern is the same on every seed exept on bedrock edition

**Comment by ZeroMemes** [comment]
Ah well /shrug.

That's the coordinate finder then?

**Comment by j13li78** [comment]
> 
> 
> The only way you can reasonably find world seeds is from bedrock formations and slime chunk locations. Programs already exist to do that.

But those require you to go to the slim chunks and baritone could autopath searching for one. 
Also some server have peaceful gamemode therefor finding slime chunks isn't really possible.

**Comment by BuyMyMojo** [comment]
very late response but there has been a fabric mod released that does it automatically just from playing, seems more possible then everr to implament into a hacked client

https://github.com/KaptainWutax/SeedCracker

**Comment by dominikaaaa** [comment]
It's only for new versions of Minecraft, and this issue was already closed as resolved
