### ISSUE TITLE
Server and Cheat Crasher

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactIssues#212]
Maybe crasher for Servers and other cheats.

**Comment by zPeanut** [comment]
is that even possible

**Comment by ZeroMemes** [comment]
Crashing other cheats would only be possible by carrying out a chat message that can lead to a null pointer, in other words, it won't be happening. To crash the server you're connected to, I'd probably have to take a look at the server play handler and find anything that can be exploited.

**Comment by LeafHacker** [comment]
Crashing a server is pretty vague really, one way might be to cause extreme lag by loading chunks really quickly (e.g. fly/speed), another by spamming items/entities if the server is creative. Or you might exploit some unhanded edge case, but realistically any exception you could trigger status will be caught by a catch all somewhere.

Without more details on a specific implementation of "crasher" this issue should probably be closed. Otherwise I could mark it as a feature request for adding more crashes into Impact.

**Comment by AutoKaspersky** [comment]
Just a gentle bump on the server crasher part, would like to know if this is currently possible and if plans to implement this have been made?

**Comment by 0-x-2-2** [comment]
🦍
