### ISSUE TITLE
Any way to communicate with Impact trough mods?

### ISSUE THREAD

**Issue by 3top1a** [ImpactDevelopment/ImpactIssues#2252]
I'm making a Minecraft mod and I need to communicate with the Impact client.
Eg. Turn on/off some cheats, set some settings, etc.

The current way I do this is by using
`Minecraft.getMinecraft().player.sendChatMessage(".toggle freecam");`

However, this buggs it out and throws an error in the game output.

Is there a better way to communicate with the Impact client?

**Comment by LeafHacker** [comment]
Impact doesn't really have an API per-se and since it is obfuscated, the actual method/class names will be different for every version. Based on that, chat commands are probably the best bet.

Could you expand more on what the error is and how often it shows up? Could you share the game output you mentioned?

`player.sendChatMessage` _should_ work; that's what macros uses to "run" the macro, so if that works so should your code.

**Comment by 3top1a** [comment]
Here is a video and the logs
[vid.tar.gz](https://github.com/ImpactDevelopment/ImpactIssues/files/4586553/vid.tar.gz)
[debug.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4586557/debug.log)
[latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4586558/latest.log)

**Comment by 0-x-2-2** [comment]
> Here is a video and the logs
> [vid.tar.gz](https://github.com/ImpactDevelopment/ImpactIssues/files/4586553/vid.tar.gz)
> [debug.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4586557/debug.log)
> [latest.log](https://github.com/ImpactDevelopment/ImpactIssues/files/4586558/latest.log)

Minecraft is NOT thread-safe stop trying to attempt to do unsafe actions on another thread.
