### ISSUE TITLE
no install button

### ISSUE THREAD

**Issue by thelilbox** [ImpactDevelopment/ImpactIssues#2450]
When i run the installer where i can chose if i want vanilla or forge i can chose if i want optifine and
 what version i want. in the tutorials i watched on how to install it there was an install button at the bottom of the installer but for me there was no install button meaning i cant install it

**Comment by dominikaaaa** [comment]
There is an install button, you need to select the version you want first.

**Comment by dominikaaaa** [comment]
![maim-2020-06-17-12-17-31](https://user-images.githubusercontent.com/17222512/84922932-8d455100-b094-11ea-8f10-397cfda50896.png)
![maim-2020-06-17-12-17-13](https://user-images.githubusercontent.com/17222512/84922933-8d455100-b094-11ea-8c24-af07ed79466a.png)
![maim-2020-06-17-12-17-06](https://user-images.githubusercontent.com/17222512/84922934-8ddde780-b094-11ea-86a8-eb019ebee82d.png)
For the forge version, it's called "save as", instead of install, because you're saving the forge jar that you want

**Comment by ScanmanTM** [comment]
This is an actual issue for some people, iirc someone on the staff team said about going into compatibility mode on Windows.

**Comment by dominikaaaa** [comment]
bruh what a windows moment

**Comment by ScanmanTM** [comment]
![image](https://user-images.githubusercontent.com/46611235/84984170-3726eb00-b132-11ea-9d2f-66aaebe9ab4f.png) was just looking for the solution and seems linux aswell.

**Comment by dominikaaaa** [comment]
That's probably because they're using a non LTS release which just so happens to not have proper HI DPI support, and their screen is 4k (most likely). Either way, that bug should be filed on the installer repo
