### ISSUE TITLE
New chunk finder

### ISSUE THREAD

**Issue by Monkfish9011** [ImpactDevelopment/ImpactIssues#2459]
Hi team. I seem to be having problems with new chunks finder on a server i play. the server is fresh and im way out in the million (hardly anyone plays also) when i turn new chunks on it shows scatterd chunks in some biomes and nothing in others, jungle seems to be the only biome the new chunks finder works properly in. and suggestions on what im doing wrong?

**Comment by VelcroKitty** [comment]
*servers on paper*

**Comment by dominikaaaa** [comment]
Fill out the template

**Comment by LeafHacker** [comment]
> Fill out the template

What useful info would the template provide? Given there's no label, this issue was probably created using the _blank_ New Issue rather than one of the templates.

New Chunks is a particularly fragile exploit, it's more likely not to work than to work. When it doesn't work there's nothing you can do, as it is entirely down to how the server tells us about chunks we load.

**Comment by dominikaaaa** [comment]
Oh, mobile cut off their last sentence which I didn't notice, oops :/
