### ISSUE TITLE
How to use schematica mod with impact?

### ISSUE THREAD

**Issue by HarroBruh** [ImpactDevelopment/ImpactIssues#3130]
How do i add and use schematica with impact on 1.12.2, I have forge and the mods required in the mods folder but nothing comes up when I load into minecraft under the impact installation.

**Comment by Callihan-ops** [comment]
More information would be required. Have you installed impact for forge? You could also check under controls or mods to check if Schematica is installed.

**Comment by CEONOS** [comment]
would it? i dont think so. problem is impact is now an installer not a jar, you dont run it in forge it is its own cluster f of garbage. bad client is bad. only reason i even went to use it was to use shcematica. what a joke. use meteor client and litematica.

**Comment by CesiumCs** [comment]
saying anything is bad just because it doesnt support your specific use case isnt very fair, but thats beside the point of the issue anyway. 
HarroBruh, if you're still having this problem, could you open a new issue with more details like what your mod folder looks like and any logs spat out by the game when its supposed to be loading what you need?
