### ISSUE TITLE
client not installing on windows

### ISSUE THREAD

**Issue by zeus0001** [ImpactDevelopment/ImpactIssues#3317]
**Describe the bug**
cant install client

**To Reproduce**
install vanilla version of 1.16.5
open game in that version
close game
open installer
click install for 1.16.5
get the error "make sure vanilla version is installed" 

**Expected behavior**
to work?

**Screenshots**

![unknown](https://user-images.githubusercontent.com/63371157/140890860-2f39c8ae-3c6b-4262-b06b-f00e39cd5011.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.9.1
- Using Optifine? NO
- Using LiteLoader? NO
- Enabled mods: no
- Operating System: Windows 10 64 bit

</details>

**Additional context**

**Comment by satzmann666** [comment]
See my issue here https://github.com/ImpactDevelopment/ImpactIssues/issues/3316

I have inspected the installer code and the message is showing because the installer checks for file _launcher_profiles.json_, but that file is renamed to _launcher_profiles_microsoft_store.json_ in MS store minecraft installation. 

Workaround is to create _launcher_profiles.json_ file (by making a copy of the _launcher_profiles_microsoft_store.json_ and renaming it to _launcher_profiles.json_) in the installation folder and then Impact installation works as intended.
