### ISSUE TITLE
NullPointerException loading singleplayer world

### ISSUE THREAD

**Issue by 9ineOff** [ImpactDevelopment/ImpactIssues#604]
**What happens?**
Instead of starting a single player world client just attempted to connect to an server... This very strange behavior fixed itself after resetarting client. 
Here's a video of it as well... 
https://youtu.be/l66AnkXWVUk
 
- Impact Version: 4.2 for 1.12.2
- Operating System: "Windows 7 64bit"

**Comment by SuperOP535** [comment]
that does not mean that it's trying to connect to a server, nullpointerex is common

**Comment by LeafHacker** [comment]
Which mods are enabled when loading the world? The error is very generic, so it will be hard to figure out what the issue is without some more info. Ideally you would be able to narrow down the cause to a single Impact module (or combination of module/world state).

Does this only happen with one world, a few or all?

**Comment by dominikaaaa** [comment]
Closed as stale
