### ISSUE TITLE
AutoTool should use seeds not crops

### ISSUE THREAD

**Issue by Bottersnike** [ImpactDevelopment/ImpactIssues#637]
Currently, autotool will switch to the crop when harvesting, not the seed. For example, if I have standard seeds on my hotbar along with wheat, when harvesting wheat I will be switched off the seeds and to the wheat. It would be more useful if the seeds were instead switched to in priority over the crop to allow one to plant back instead of having to harvest then plant it afterwards.

**Comment by MightyKnight** [comment]
Since Impact 4.4 the the AutoTool doesn't switch away from the seeds. This closes this bug.

Please create a [Suggestion](https://github.com/ImpactDevelopment/ImpactIssues/issues/new?assignees=&labels=Suggestion&template=feature_request.md&title=Please+add+a+brief+but+descriptive+title) issue for the second part of your issue (switching to seeds in AutoTool) if you deem it important.
