### ISSUE TITLE
RPC doesn't work.

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactIssues#904]
### What happens?
Discord Rich Presence doesn't work.
### Exact steps to reproduce?
Try turning it on.

- Impact Version:  Latest 1.12.2 4.4
- Using Optifine?  Yes papa
- Using LiteLoader?  No papa
![image](https://user-images.githubusercontent.com/35407179/50880932-f755c300-13d7-11e9-8482-839b92c927fd.png)

**Comment by EmeraldSnorlax** [comment]
It works fine on openSUSE 'weed for me. Think it's a windows thing.

**Comment by Cerbiac** [comment]
On Impact 4.6 for Minecraft 1.12.2, and my Discord RPC worked after my modified launcher TLauncher downloaded something for Impact (which is odd, should already be downloaded, you know). So maybe it fails b/c not all of the libraries download, but I can't confirm for sure. Just more of a hunch more than anything. I'll update if it stops working or what happens when I delete the library and reload using the normal launcher, than the TLauncher.

**Comment by Cerbiac** [comment]
Can confirm: the Minecraft launcher claims it can't download `java-discord-rpc` (it can download `discord-rpc-releases`), and refuses to start the game. TLauncher just downloaded the missing file and ran, and `Discord RPC` functioned fine. So IG it has to downloaded manually instead of through the Minecraft Launcher, or else it won't work.

**Comment by dominikaaaa** [comment]
Closed as stale, can't reproduce. Works fine on Minecraft launcher and MultiMC
